language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.1
otp_release:
  - 19.0
  - 20.0
matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.0
services:
  - postgresql
addons:
  postgresql: "9.4"
